services:
  - type: web
    name: landing-page
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run db:setup
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: landing-db
          property: connectionString
      - key: CORS_ORIGIN
        value: "*"

databases:
  - name: landing-db
    databaseName: landing
    user: landing_user
